# Generated by Django 5.1.4 on 2024-12-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio_ru',
        ),
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
